### ISSUE TITLE
DDK and CDK deploy not working as stated in the workshop

### ISSUE THREAD

**Issue by LeonLuttenberger** [awslabs/aws-ddk#132]
### Describe the bug

DDK deploy is failing with:

```
Deploying DDK stacks to AWS account 619876764317 and region us-east-1...
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import aws_cdk as cdk
ModuleNotFoundError: No module named 'aws_cdk'
```

CDK deploy is failing with:

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import aws_cdk as cdk
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 24837, in <module>
    from . import aws_apigateway
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1565, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 184, in <module>
    from ..aws_cloudwatch import (
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 602, in <module>
    from ..aws_iam import Grant as _Grant_a7ae64f8, IGrantable as _IGrantable_71c4f5de
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 662, in <module>
    class AddToPrincipalPolicyResult:
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 667, in AddToPrincipalPolicyResult
    policy_dependable: typing.Optional[constructs.IDependable] = None,
AttributeError: module 'constructs' has no attribute 'IDependable'
```

### How to Reproduce

I followed the steps in the DDK workshop, and ran into the following issue when running `ddk deploy`:

```
Deploying DDK stacks to AWS account 619876764317 and region us-east-1...
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import aws_cdk as cdk
ModuleNotFoundError: No module named 'aws_cdk'
```

My assumption was that it was related to the virtual environment, and `ddk` running the wrong version. This proved correct when I ran `which ddk`, as it printed a reference to the `ddk` installation outside the virtual env.

I then tried to run `cdk deploy` instead. However, it failed with the following error:
```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import aws_cdk as cdk
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 24837, in <module>
    from . import aws_apigateway
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1565, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 184, in <module>
    from ..aws_cloudwatch import (
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 602, in <module>
    from ..aws_iam import Grant as _Grant_a7ae64f8, IGrantable as _IGrantable_71c4f5de
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 662, in <module>
    class AddToPrincipalPolicyResult:
  File "/Users/lutleon/Projects/ddk-demo/sample-app/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 667, in AddToPrincipalPolicyResult
    policy_dependable: typing.Optional[constructs.IDependable] = None,
AttributeError: module 'constructs' has no attribute 'IDependable'
```

I was able to mitigate this by running `pip install aws_cdk.constructs`. After I ran that command, `cdk deploy` was able to synthesize the resources and show the diff.

I am on version 2.34.0 (build 633edab) of CDK. Additionally, the Python library for `aws-cdk-lib` is on version 2.29.0.

### Environment

```
Provide your `pip list` output, particularly the version of the AWS DDK library you used. Providing this information may significantly improve resolution times.
```

### OS

Mac

### Python version

3.8.10

### AWS DDK version

0.5.1

**Comment by LeonLuttenberger** [comment]
Upgrading CDK to version 2.34.2 fixed the problem with `cdk deploy`.

**Comment by LeonLuttenberger** [comment]
can't reproduce
